const user = JSON.parse(localStorage.getItem('user'));
const state = user
    ? { status: { loggedIn: true }, user }
    : { status: 'not_logged_in', user: null };

const actions = {
    login({commit}) {
        commit('login');
        alert('loginning in vuex')
    },
    logout({ commit }) {
        commit('logout');
    },
};

const mutations = {
    login(state) {
        state.status = 'logged_in';
    },

    logout(state) {
        state.status = 'not_logged_in';
    },
};

export const account = {
    namespaced: true,
    state,
    actions,
    mutations
};
